### ISSUE TITLE
Concurrency exception on Windows 

### ISSUE THREAD

**Issue by razvanz** [Stratio/stratio-cassandra#12]
After updating to `stratio-cassandra-2.1.3.0` I can see cassandra server throwing a lot of concurrency errors:

```
 java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: java.io.FileNotFoundException: C:\InstalledApps\stratio-cassandra\data\data\system\schema_columns-296e9c049bec3085827dc17d3df2122a\system-schema_columns-tmplink-ka-151-Data.db (The process cannot access the file because it is being used by another process) 
```

Any help with this?

**Comment by adelapena** [comment]
This seems related to http://www.mail-archive.com/user@cassandra.apache.org/msg41217.html#
If so, this issue is not related to the functionalities (Lucene indexing) added to Apache Cassandra by Stratio, so further questions about this topic must be directed to the [Apache Cassandra user list](http://planetcassandra.org/apache-cassandra-mailing-lists/) and/or to [Apache Cassandra JIRA](https://issues.apache.org/jira/browse/cassandra/). We will merge the fix as soon as it is available.
