### ISSUE TITLE
Can't create index on column which is clustering ordered

### ISSUE THREAD

**Issue by zxdy** [Stratio/stratio-cassandra#14]
hello, recently i find a case like following:

first create a new table
```
CREATE TABLE IF NOT EXISTS quote.historical_prices (
    id timeuuid,
    time timestamp,
    lucene text,
    PRIMARY KEY (id,time)
) WITH CLUSTERING ORDER BY(time DESC);

```

and then when creating index on time column , it got failed 

```
CREATE CUSTOM INDEX historical_prices_index ON quote.historical_prices ( lucene ) USING
'org.apache.cassandra.db.index.stratio.RowIndex' WITH OPTIONS = {
	'refresh_seconds' : '1',
	'schema' : '{
        fields : {
			time : {type : "date", pattern  : "yyyy/MM/dd"}
        }
    }'
};
```

 do you have any ideas?

**Comment by adelapena** [comment]
You are right, it is a bug related to the type checking. I have just fixed it in [develop branch](https://github.com/Stratio/stratio-cassandra/tree/develop). The changes will be merged to master ASAP.
Thanks!

**Comment by zxdy** [comment]
Thank you  for your so quick feedback!

**Comment by zxdy** [comment]
Hello Adelapena,
I have another question about the refresh_seconds when create index . In you documents it is describe as " number of seconds before refreshing the index (between writers and readers). Defaults to ’60′."

if i have a very big table , and everyday i have multiple threads to load big data to this table, what is the  best way to determine the refresh_seconds ? if the value is too small , will the refresh get hung because of the large volume?if the index start to refresh while multiple threads still loading data , will it wait until all threads complete writing?

Thanks

**Comment by adelapena** [comment]
Hi Ario,

About concurrency, the refresher thread does not wait for current indexing operations, so you do not need to worry about this. Searches are done over a "point in time" snapshot taken in the last index refresh, and you won't see the newly indexed data until the next refresh. 

Refreshing is a fast operation, taking less than a second, but it's computationally expensive. So, a high refresh rate should not get hung but it will slow down your cluster due to the high resource consumption, slowing down indexing and searching. 

The default  value (60 seconds) is generally good even with large volumes of data. It's no possible to analytically determine the impact of refresh rate on general cluster performance, so you should experimentally find a compromise between performance and data's freshness. 

I hope this helps.
