### ISSUE TITLE
Why Lucene instead of Solr was selected as the two level index to impl?

### ISSUE THREAD

**Issue by Dourm** [Stratio/stratio-cassandra#15]
Why Lucene instead of Solr was selected as the two level index to impl?

**Comment by adelapena** [comment]
Because Lucene is a library that can run embedded in Cassandra, without the need to run any external service. Our purpose was to transparently expand the CQL capabilities for several use cases, including both complex search and Spark/Hadoop integration. If you are searching a way to integrate Cassandra with Solr, you may be interested in [DSE Enterprise](http://www.datastax.com/what-we-offer/products-services/datastax-enterprise), which takes a different approach.
