### ISSUE TITLE
Aggregate In Stratio Cassandra

### ISSUE THREAD

**Issue by justinjoseph89** [Stratio/stratio-cassandra#17]
Hi,
I know it is not possible to do aggregate functions like MAX() and SUM() in Apache -Cassandra. I just want to know that is there any way i can achieve this functionality using stratio-cassandra?
Thanks

**Comment by adelapena** [comment]
Hi,

No, currently it is not possible to perform these kind of aggregations with Stratio Cassandra. However it is a  very interesting feature, and it may be added with relative ease in the future. We could use the [SecondaryIndexSearcher#postReconciliationProcessing](https://github.com/Stratio/stratio-cassandra/blob/develop/src/java/org/apache/cassandra/db/index/SecondaryIndexSearcher.java#L136)  method (see [CASSANDRA-8717](https://issues.apache.org/jira/browse/CASSANDRA-8717)) for doing the aggregations once the indexed results are retrieved by the coordinator node. You could also find http://planetcassandra.org/blog/user-defined-functions-in-cassandra-3-0/ interesting. 

Note than in both solutions, as far as I know, the aggregation must be done in the coordinator node. This is due to the fact that aggregation should be done after the reconciliation of the replicas, which is done in the coordinator node. If the data to be aggregated is too large to fit in a single machine, then you should use Spark or Hadoop for this. Both are fully compatible with Stratio Cassandra, which could be useful if you want to [prefilter the aggregated data at database level](https://www.youtube.com/watch?v=e6psIxiQ_ec).
