### ISSUE TITLE
ant release is hanging

### ISSUE THREAD

**Issue by craveica** [Stratio/stratio-cassandra#24]
ant release fails to complete (tested on master and develop). However, ant build is working.

**Comment by adelapena** [comment]
```ant release``` is really slow because it runs [Apache Rat](http://creadur.apache.org/rat/) plugin to verify [ASF authoring and copyright rules](http://www.apache.org/legal/src-headers.html). Indeed, it is so slow that it may seem hung. Could this be the problem? It usually takes almost one hour to complete. 
You could speed up the release generation by skipping Rat auditory, what can be done by removing lines [1064](https://github.com/Stratio/stratio-cassandra/blob/stratio-cassandra-2.1.4.1/build.xml#L1064) to [1080](https://github.com/Stratio/stratio-cassandra/blob/stratio-cassandra-2.1.4.1/build.xml#L1080) in [build.xml](https://github.com/Stratio/stratio-cassandra/blob/stratio-cassandra-2.1.4.1/build.xml#L1064).

**Comment by craveica** [comment]
Thank you.
