### ISSUE TITLE
Relevance score question

### ISSUE THREAD

**Issue by craveica** [Stratio/stratio-cassandra#29]
Is it possible to alter/customize relevance score? 

If not, are there any plans to support it?

**Comment by adelapena** [comment]
Custom relevance scoring is not supported, but it is on our roadmap. Currently we are quite busy modifying Stratio Cassandra to be distributed as an Apache Cassandra plugin instead of a fork (see [CASSANDRA-8717](https://issues.apache.org/jira/browse/CASSANDRA-8717)), but we are looking forward to start working on this as soon as we have the plugin distribution ready. Maybe we could do it better if you could give me more details about your use case.

**Comment by craveica** [comment]
+1 for CASSANDRA-8717

I don't have a particular use case. I was thinking it would be a nice addition to stratio-cassandra.

Thank you.
