### ISSUE TITLE
OperationTimedOut When taking count

### ISSUE THREAD

**Issue by justinjoseph89** [Stratio/stratio-cassandra#38]
Hi,
Is there any limit for data inserted in Cassandra to view its total count?
For example one of my table contains **120000** data, but whenever i tries to take its count,
`select count(*) from tweets;`
I am getting following error,
`OperationTimedOut: errors={}, last_host=Private IP`
What will be the issue?

**Comment by adelapena** [comment]
No, there is no hard limit for the amount of rows to be collected by a query.

Count queries in Cassandra are a little bit tricky, because C* needs to bring all the implied rows to the coordinator node to do replica agreement. This way, a COUNT(*) query is almost so heavy as a SELECT(*). This is a limitation of Apache Cassandra that Lucene index can not solve.

Thus, you have two options here. One is to increase the timeout thresholds in cassandra.yaml and in client configuration. The other one is using Spark or Hadoop support to perform queries implying a large amount of results.

In another vein, this repository has been discontinued in favour of [Stratio's Cassandra Lucene Index](https://github.com/Stratio/cassandra-lucene-index), which maintains exactly the same features being a plugin of Apache Cassandra instead of a fork. Future issues must be directed to this new project.

**Comment by justinjoseph89** [comment]
Thanks.
