### ISSUE TITLE
Cassandra maps and Lucene 

### ISSUE THREAD

**Issue by lucevers** [Stratio/stratio-cassandra#39]
Used configuration:  test-user-create.cql
mapz:{type:"string"}    -->  So a map is a string for Lucene.

Howto search a Cassandra Map in Lucene?

Testing setz,listz: query is oke but for mapz I don't get a result:

SELECT *
FROM test.users
WHERE stratio_col = '{query : {
                        type : "wildcard",
                        field: "mapz",
                        value : "*" }}'

I checked with other fieldvalues like mapz.key  etc but no result.

**Comment by adelapena** [comment]
You should specify the key of the map, e.g. if you have the following rows:
```
INSERT INTO users (name, gender, age, animal, mapz) VALUES ( 'pepito_0', 'male', -2, 'monkey', {'k1':'v1','k2':'v2'});
INSERT INTO users (name, gender, age, animal, mapz) VALUES ( 'pepito_0', 'male', 1, 'monkey',  {'k1':'v1','k2':'v2'});
```
You can query this way:
```
SELECT *
FROM test.users
WHERE stratio_col = '{query : {
type : "wildcard",
field: "mapz.k1",
value : "*" }}'
```
Or also:
``` 
SELECT *
FROM test.users
WHERE stratio_col = '{query : {
type : "wildcard",
field: "mapz.k2",
value : "*" }}'
```
In another vein, this repository has been discontinued in favour of [Stratio's Cassandra Lucene Index](https://github.com/Stratio/cassandra-lucene-index), which maintains exactly the same features being a plugin of Apache Cassandra instead of a fork. Future issues must be directed to this new project.

**Comment by lucevers** [comment]
Thanks!
