### ISSUE TITLE
Indexing dashes

### ISSUE THREAD

**Issue by razvanz** [Stratio/stratio-cassandra#40]
In a indexed table I need to retrieve values matching a text possibly containing dashes (`-`). The index query I wrote was only working for non-dash values.

The table:

```
CREATE COLUMNFAMILY IF NOT EXISTS entity
(partitionid timeuuid,
  entityid text,
  customindex text,
  PRIMARY KEY(partitionid, entityid));
```

The index:

```
CREATE CUSTOM INDEX entity_filter
ON entity.entity (customindex)
USING 'org.apache.cassandra.db.index.stratio.RowIndex'
WITH OPTIONS = {
    'refresh_seconds': '1',
    'schema' : '{
        default_analyzer : "org.apache.lucene.analysis.standard.StandardAnalyzer",
        fields : {
            partitionid: {type: "uuid"},
            entityid: {type: "text"}
        }
    }'
};
```

Some values:

```
INSERT INTO entity (partitionid, entityid) VALUES ( b23d2db0-3057-11e5-82ae-455b314f19b8, 'dash-value');
INSERT INTO entity (partitionid, entityid) VALUES ( b23d2db0-3057-11e5-82ae-455b314f19b8, 'nodash');
```

Querying for the `dash-value` no result is given while the `nodash` value returns the row:

```
SELECT * FROM entity WHERE partitionid = b23d2db0-3057-11e5-82ae-455b314f19b8 and customindex = '{"query":{"type":"boolean","must":[{"type":"match","field":"entityid","value":"dash-value"}]}}';
```

I checked for `_` and it seems to work, but before doing any major changes is there a way to make dashes work? (Maybe with a different analyzer?)

**Comment by adelapena** [comment]
Hi,

You are using a `text` mapper for the column `entityid` with the [Lucene's standard analyzer](http://lucene.apache.org/core/5_1_0/analyzers-common/org/apache/lucene/analysis/standard/StandardAnalyzer.html). This analyzer interprets dashes as a token separator, so it splits `dash-value` into two tokens, `dash`and `value`. So, the following queries produce results:

```
SELECT * FROM entity WHERE partitionid = b23d2db0-3057-11e5-82ae-455b314f19b8 and customindex = '{"query":{"type":"boolean","must":[{"type":"match","field":"entityid","value":"dash"}]}}';
SELECT * FROM entity WHERE partitionid = b23d2db0-3057-11e5-82ae-455b314f19b8 and customindex = '{"query":{"type":"boolean","must":[{"type":"match","field":"entityid","value":"value"}]}}';
```

If you are interested in tokenization, you should choose a proper analyzer, for example:

```
CREATE CUSTOM INDEX entity_filter
ON entity.entity (customindex)
USING 'org.apache.cassandra.db.index.stratio.RowIndex'
WITH OPTIONS = {
    'refresh_seconds': '1',
    'schema' : '{
        default_analyzer : "org.apache.lucene.analysis.standard.StandardAnalyzer",
        fields : {
            partitionid: {type: "uuid"},
            entityid: {type: "text", analyzer:"org.apache.lucene.analysis.core.WhitespaceAnalyzer"}
        }
    }'
};
```

Alternatively, if you don't want you text to be tokenized, you should use a `string` mapper:

```
CREATE CUSTOM INDEX entity_filter
ON entity.entity (customindex)
USING 'org.apache.cassandra.db.index.stratio.RowIndex'
WITH OPTIONS = {
    'refresh_seconds': '1',
    'schema' : '{
        default_analyzer : "org.apache.lucene.analysis.standard.StandardAnalyzer",
        fields : {
            partitionid: {type: "uuid"},
            entityid: {type: "string"}
        }
    }'
};
```

In another vein, this repository has been discontinued in favour of [Stratio's Cassandra Lucene Index](https://github.com/Stratio/cassandra-lucene-index), which maintains exactly the same features being a plugin of Apache Cassandra instead of a fork. Future issues must be directed to this new project.

**Comment by razvanz** [comment]
Using the `WhitespaceAnalyzer` helped the cause. Closing...
