### ISSUE TITLE
The website of this repo can not be accessed ??

### ISSUE THREAD

**Issue by lynchlee** [Stratio/stratio-cassandra#44]
The website of this repo can not be accessed ??  someone can tell me ?
http://openstratio.org

**Comment by adelapena** [comment]
The domain openstratio.org disappeared long time ago. If you are looking for the web site of Stratio, this is at [http://www.stratio.com/](http://www.stratio.com/). If you are looking for the documentation of this project, it is at [https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.8/doc/documentation.rst](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.8/doc/documentation.rst).

**Comment by lynchlee** [comment]
@adelapena Thx !! 
But I want to tell you that the website of this repo is shown as http://openstratio.org, should be fixed ??

**Comment by adelapena** [comment]
Hi @lynchlee ,

As you can read in the [readme](https://github.com/Stratio/stratio-cassandra/blob/master/README.md), this project has been discontinued in favour of [Cassandra Lucene Index](https://github.com/Stratio/cassandra-lucene-index), which maintains exactly the same features being a plugin of Apache Cassandra instead of a fork. I just have updated the project description to reflect this.
